version: "3.8"
services:
  mariadb:
    image: mariadb:10.2.40
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_dv:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "127.0.0.1:8080:8080"

  pg:
    image: postgres:9.6
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - pg_dv:/var/lib/postgresql/data

  rabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile.rabbitmq
    image: rabbitmq:3-management-consistent-hash-exchange
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  app:
    build:
      context: ./
      dockerfile: Dockerfile.flask-app
    image: flask-app:latest
    ports:
      - "127.0.0.1:5000:5000"

volumes:
  mariadb_dv: ~
  pg_dv: ~
