FROM python:3.9

RUN pip install -U pip poetry

COPY . /opt/app
WORKDIR /opt/app

ENV FLASK_APP=alaya.demo.app:app
ENV FLASK_ENV=development

RUN poetry config virtualenvs.create false && poetry install --no-dev

CMD ["flask", "run", "--no-debugger", "--host=0.0.0.0"]
