version: "3.8"
services:
  mariadb:
    image: mariadb:10.2.40
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_dv:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "127.0.0.1:8080:8080"

  pg:
    image: postgres:9.6
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - pg_db:/var/lib/postgresql/data

volumes:
  mariadb_dv: ~
  pg_db: ~
